### ISSUE TITLE
[Question] How do I make a modpack use a different Java version by default on 1.20.1?

### ISSUE THREAD

**Issue by Mqony** [Radk6/MC-Optimization-Guide#1]
I want to ship a modpack out using GraalVM Java 21 instead of the default 17.0.8, but I can't find out how to do it. I don't even know how to change Java versions for just myself. How can I do this?

**Comment by Radk6** [comment]
> I want to ship a modpack out using GraalVM Java 21 instead of the default 17.0.8, but I can't find out how to do it. I don't even know how to change Java versions for just myself. How can I do this?

You can't ship a modpack with a different Java version, it's up to the player to change it. Like vibrantrida said, make instructions instead.
