### ISSUE TITLE
Sky Factory 4 crashes pre startup

### ISSUE THREAD

**Issue by GlitchSlayed** [Radk6/MC-Optimization-Guide#10]
Following the modpack tutorial the sf4 instance crashes after long ways into startup.

Logs: https://mclo.gs/V8MhENW

**Comment by Radk6** [comment]
Thanks for reporting. The issue you reported is already adressed (update Flux Networks to the latest version), however there's another issue related to Resource Hogs, which I cannot fix myself. The temporary solution is to downgrade StellarCore to 1.5.13.

**Comment by GlitchSlayed** [comment]
can confirm this fixed my problem. I updated Flux Net and downgraded stellar core. Should i report this issue to stellar core regarding resource hogs?

**Comment by Radk6** [comment]
I already reported it

**Comment by Radk6** [comment]
Closing this since the workaround was added to the SF4 guide.
