### ISSUE TITLE
Add Sledgehammer & Particle Culling

### ISSUE THREAD

**Issue by cgdyusijhcgfdyuei** [Radk6/MC-Optimization-Guide#14]
These would go in `1.12.md` or `not-recommended.md`

> [https://www.curseforge.com/minecraft/mc-mods/sledgehammer]()
Fixes bugs on server & client

> [https://www.curseforge.com/minecraft/mc-mods/particle-culling]()
self-explanatory

**Comment by erialsan** [comment]
Particle Culling should be used for Optifine, although that function is superior if Vintagium is available.
Sledgehammer bug fixes should have been sufficient for UT/StellarCore.

**Comment by Radk6** [comment]
> Particle Culling should be used for Optifine, although that function is superior if Vintagium is available

Vintagium isn't recommended because it's not easy to download, updates are infrequent and mod compatibility isn't the best.

>  Sledgehammer bug fixes should have been sufficient for UT/StellarCore.

So Sledgehammer is redundant?

**Comment by erialsan** [comment]
Some patches may still be needed, such as ImmersiveEngineering

**Comment by Radk6** [comment]
Alright, I'll probably keep it on the list since I haven't had any issues with it so far in my W.I.P modpack.
