### ISSUE TITLE
Cleanroom Loader can running with Java24

### ISSUE THREAD

**Issue by erialsan** [Radk6/MC-Optimization-Guide#15]
However, you will need to set up a Java compatibility skip for Prism.
I had no problem at all with Java24 ea.
I am told that there is a problem with Linux, but I have not done enough research.

**Comment by Radk6** [comment]
I'll have to try this again myself, last time I checked it crashed with some mods.

**Comment by Radk6** [comment]
Can confirm it works. I changed the recommended Java version.
