### ISSUE TITLE
[Mod Suggestion] Vintagium is a Sodium alternative for 1.12.2

### ISSUE THREAD

**Issue by Qattos** [Radk6/MC-Optimization-Guide#17]
I got it from [here](https://github.com/duckopia/sodium-1.12/releases) and followed this incompatibility [guide](https://github.com/daizu-007/Vintagium-Compatibility-List), only other mod I had to disable to make it work was RLFoliage/BetterFoliage.
Haven't tested performance yet.

**Comment by Radk6** [comment]
Vintagium's mod compatibility isn't great, and I've seen people say Nothirium performs better. I won't add it until the compatibility issues get fixed and/or a shader mod is developed for it to replace OptiFine.

**Comment by Qattos** [comment]
Correct, I tested performance with Vintagium and there seems to be some stuttering.
Hoping when Oculus is finally ported to 1.12.2 it'll be in a more stable state.

**Comment by Radk6** [comment]
Technically speaking Oculus was already ported to 1.12.2 (and can be compiled) but it crashes on startup.
