### ISSUE TITLE
Azul Zulu comparison

### ISSUE THREAD

**Issue by vibrantrida** [Radk6/MC-Optimization-Guide#2]
It would be interesting to see a comparison with Azul Zulu too, latetly I've been seeing more modpacks recommend it over GraalVM and Adoptonium but I cannot find any concrete comparison

**Comment by Radk6** [comment]
[It's being worked on](https://github.com/Radk6/MC-Optimization-Guide/blob/main/java-n-stuff/java-benchmarks.md). Currently there's only a game loading time benchmark, but benchmarks for world creation and loading times as well as fps will also be added.

**Comment by Radk6** [comment]
Benchmarks for fps and game loading times have been updated and finalized. I decided to drop Shenandoah as most players use either G1GC or Generational ZGC, and moved GraalVM from 21 to 24 (EA) due to it finally getting proper Generational ZGC support.
